# Generated by Django 4.2.2 on 2024-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_subscription_sign_of_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
