# Generated by Django 4.2.2 on 2024-06-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_course_last_update_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="sign_of_subscription",
        ),
    ]
